name: Package

on:
  workflow_run:
    workflows: [ "Compile" ]
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sourcemod-version: [ '1.12' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release archive
        run: |
          zip -r ${{ env.PLUGIN_NAME }}-${{ env.PLUGIN_VERSION }}.zip addons/ scripts/ -x "addons/sourcemod/scripting/include/*"

      - name: Create GitHub release
        run: |
          gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
          gh config set git_protocol ssh
          if ! gh release view ${{ env.PLUGIN_VERSION }} --repo ${{ github.repository }} > /dev/null 2>&1; then
            gh release create ${{ env.PLUGIN_VERSION }} ./${{ env.PLUGIN_NAME }}-${{ env.PLUGIN_VERSION }}.zip -t "${{ env.PLUGIN_VERSION }}" --repo ${{ github.repository }} --draft
          fi
